### ISSUE TITLE
500 error when entering text

### ISSUE THREAD

**Issue by britinmpls** [NextThingCo/ChippyRuxpin#4]
CHIP running 4.4 headless, fully updated.

After entering text and hitting go the page displays:

**Error: 500 Internal Server Error**
Sorry, the requested URL 'http://192.168.1.128:8080/' caused an error:
_Internal Server Error_

**Exception:**
_OSError(2, 'No such file or directory')_

**Traceback:**
_Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1737, in wrapper
    rv = callback(*a, **ka)
  File "/home/chip/ChippyRuxpin/chippyRuxpin_webFramework.py", line 29, in speak
    self.talkFunc( speech )
  File "chippyRuxpin.py", line 98, in talk
    subprocess.call(["espeak", "-w", "speech.wav", myText, "-s", "130"])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory_

**Comment by britinmpls** [comment]
Found that I was missing dependencies for espeak libs. Installed those and everything works!
